<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>CS8524</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Spinneret.Mediator\Spinneret.Mediator.csproj" />
        <ProjectReference Include="..\Spinneret.Functional\Spinneret.Functional.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Spinneret.Tests" />
    </ItemGroup>

</Project>
