<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>CS8524</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Spinneret.Functional\Spinneret.Functional.csproj" />
        <ProjectReference Include="..\Spinneret.Parsing\Spinneret.Parsing.csproj" />
    </ItemGroup>

</Project>
