<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>CS8524</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NodaTime" Version="3.3.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Spinneret.Mediator\Spinneret.Mediator.csproj" />
    </ItemGroup>

</Project>
